### ISSUE TITLE
Can't setup project according to README

### ISSUE THREAD

**Issue by fEyebrow** [toeverything/AFFiNE.pro#58]
when I used "pnpm install", I got the error:
<img width="974" alt="image" src="https://github.com/toeverything/AFFiNE.pro/assets/18180417/0d333bef-06a1-403e-9d88-3173d0d01b1a">

when I used "yarn install", the project successfully started:
<img width="327" alt="image" src="https://github.com/toeverything/AFFiNE.pro/assets/18180417/05808e7b-aac9-4c50-95f1-1fa93c72ffb5">

I find the "exports" in @nuxt/kit/package.json, I don't know the reason for using “pnpm install“ and failing

**Comment by himself65** [comment]
we are not using `pnpm` in this project

**Comment by himself65** [comment]
pnpm has different link strategies with yarn. I think we are not planning to support multiple package managers.

Closing as won't fix
