### ISSUE TITLE
Image lazy not work by forward or go back

### ISSUE THREAD

**Issue by lawvs** [toeverything/AFFiNE.pro#76]
After using the browsing history's forward and backward functions, the images cannot be displayed.

https://github.com/toeverything/AFFiNE.pro/assets/18554747/eedaf01d-ea2e-400a-b86a-830c73401280

**Comment by SuneBear** [comment]
This looks weird, could you provide the reproduction steps?

**Comment by lawvs** [comment]
This issue is straightforward to reproduce on my computer. You can try using incognito mode or disable the cache.

Chrome Version 114.0.5735.198 (Official Build) (arm64)

https://github.com/toeverything/AFFiNE.pro/assets/18554747/69711d1c-3290-4af8-8b20-6726d736d49d
