### ISSUE TITLE
Serious frame drop on the homepage, especially on the first screen(< 30 fps)

### ISSUE THREAD

**Issue by MaybeMonad** [toeverything/AFFiNE.pro#80]
<img width="1955" alt="Screenshot 2023-08-11 at 11 56 12" src="https://github.com/toeverything/AFFiNE.pro/assets/24782674/bd383dac-6602-4c86-94a1-10070f5b4cb1">

**Comment by SuneBear** [comment]
Could you provide the running env? My computer (Apple M1) runs at a normal framerate～
<img width="941" alt="Screenshot 2023-08-15 at 19 43 05" src="https://github.com/toeverything/AFFiNE.pro/assets/7693264/1ddb9eae-3aa8-4f60-ad0f-c29630a80b5f">
