### ISSUE TITLE
remove beta and canary version card in 0.7.x and 0.6.x

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE.pro#82]
We no longer maintain those versions

**Comment by himself65** [comment]
My suggestion is only keep beta and canary version in our latest major version

**Comment by SuneBear** [comment]
Thx for your feedback, I have disabled buttons in the older versions https://github.com/toeverything/AFFiNE.pro/commit/65aa56bb177a1a30f18f230bd1298961d2706305
