### ISSUE TITLE
NDM/IDM auto download copilot video

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE.pro#84]
https://github.com/toeverything/AFFiNE.pro/blob/a2280791656486a59f0376755af50fdf3aa5ff3e/components/views/campaign-entry.vue#L12-L13

![telegram-cloud-photo-size-5-6294273215534577301-y](https://github.com/toeverything/AFFiNE.pro/assets/14026360/3e1f5a05-5956-4939-a4da-44618ded6539)

When you open affine.pro with NDM extension enabled, copilot.mp4 will be auto downloaded. This will break user experience.

**Comment by himself65** [comment]
Please follow this guide to improve the UX

https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

**Comment by SuneBear** [comment]
Fixed by updating the video https://github.com/toeverything/AFFiNE.pro/commit/317e058180a89d990397142d944ebd9ee00f7ae6
