### ISSUE TITLE
Wrong publish date on blog content page

### ISSUE THREAD

**Issue by Garfield550** [toeverything/AFFiNE.pro#87]
<img width="545" alt="image" src="https://github.com/toeverything/AFFiNE.pro/assets/3471836/ade4ef87-0dba-45cb-a407-febb7bd22779">
<img width="814" alt="image" src="https://github.com/toeverything/AFFiNE.pro/assets/3471836/5176a02a-5edb-4a3c-85c0-fc135331ea23">

**Comment by SuneBear** [comment]
Great feedback, fixed it via https://github.com/toeverything/AFFiNE.pro/commit/de441b0775bf288de511fa5456723a9902349644
