### ISSUE TITLE
Update the Twitter logo to X

### ISSUE THREAD

**Issue by Shreyas0410** [toeverything/AFFiNE.pro#93]
To Reproduce -
Go to the footer of the website.

In the current version of the website the logo of Twitter is not updated.
![Screenshot 2023-10-16 201125](https://github.com/toeverything/AFFiNE/assets/70795867/28627be1-f8a6-4cbd-abac-fcc7cff4847a)

**Comment by hwangdev97** [comment]
I think this issue should be in this repo. 

@niranjan-kurhade are you willing to continue working on this issue?

**Comment by niranjan-kurhade** [comment]
> I think this issue should be in this repo.
> 
> @niranjan-kurhade are you willing to continue working on this issue?

Yes! @hwangdev97

**Comment by SuneBear** [comment]
Updated in v3
